ai.provider=openai

gemini.api.key=${GEMINI_KEY}
gemini.base.url=https://generativelanguage.googleapis.com/v1beta
gemini.model=gemini-2.5-pro
gemini.retry.max.attempts=3
gemini.retry.initial.delay.ms=500
gemini.retry.max.delay.ms=5000

openai.api.key=${OPENAI_API_KEY}
openai.base.url=https://api.openai.com/v1
openai.model=gpt-4.1-mini
openai.retry.max.attempts=3
openai.retry.initial.delay.ms=500
openai.retry.max.delay.ms=5000

server.port=9999
